name: Build PDF Toolbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt5
        pip install PyPDF2
        pip install Pillow
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=icon.ico --add-data "icon.ico;." pdf/pdf_merger.py --name PDFToolbox

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFToolbox-Windows
        path: dist/PDFToolbox.exe